# Generated by Django 4.0.1 on 2022-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
